Feature/filtros produtos
SkyFlyTeam/cloudStock pull request #73
Opened 2024-11-05 01:29 UTC by gui-benedito

Adicionando campos de filtros #65

2024-11-05 11:05 UTC, BrennoLyrio commented
Ao ver a responsividade é interessante dar um espaçamento maior entre os campos.

2024-11-05 14:49 UTC, karengoncalves8 requested changes
Ótimo trabalho! Alguns apontamentos:
- No filtro de Saída e Entrada há os filtros por produto e fornecedor, mas isso não é uma informação da tabela; Ainda sobre essas telas, foi adicionado o campo de Data então seria interessante já adicionar, mesmo que deixe comentado pra adicionar quando der o merge;
- Os campo de data deveriam ter o conteúdo mínimo pra exibir a data completa (min-width: fit-content) 
- Como já apontado pelo @BrennoLyrio, seria interessante adicionar um espaçamento maior (gap) nos campos, tanto entre os input quanto nas div em si

2024-11-05 19:32 UTC, gui-benedito commented
Nas páginas de Saída e Entrada foi adicionado campo para filtragem por data. Ainda não puxei a coluna de data de outra branch, será feito no PR, mas funcionalidade está ok.
Ajustado os campos de inputs tipo data, espaçamentos entre elementos e responsividades

2024-11-07 00:50 UTC, karengoncalves8 approved these changes
Tudo certo!

2024-11-07 11:23 UTC, merged